/*
 * Copyright (c) 2026 Meshtastic LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.meshtastic.core.automation.repository

import kotlinx.coroutines.flow.Flow
import org.meshtastic.core.automation.model.AutomationLog
import org.meshtastic.core.automation.model.AutomationRule

/**
 * Persistence contract for automation rules and their execution history.
 *
 * All methods are safe to call from any coroutine context; implementations must dispatch DB operations to an IO
 * dispatcher internally.
 */
interface AutomationRepository {

    /** Emits the full list of rules (enabled and disabled) ordered by creation time. */
    fun observeRules(): Flow<List<AutomationRule>>

    /**
     * Emits only the currently enabled rules.
     *
     * The [AutomationEngine] subscribes to this to know which rules to start/stop without reacting to disabled-rule
     * edits.
     */
    fun observeEnabledRules(): Flow<List<AutomationRule>>

    /** Returns a single rule snapshot, or null if not found. */
    suspend fun getRule(id: String): AutomationRule?

    /**
     * Inserts or updates a rule.
     *
     * The [id] field on [rule] is treated as the primary key; a new UUID should be generated by callers (e.g. via
     * `kotlin.uuid.Uuid.random().toString()`) before first save.
     */
    suspend fun saveRule(rule: AutomationRule)

    /** Permanently deletes a rule and all its log entries (cascade delete). */
    suspend fun deleteRule(id: String)

    /** Enables or disables a rule without changing any other fields. */
    suspend fun setEnabled(id: String, enabled: Boolean)

    /**
     * Records that a rule fired successfully at [timestamp] and increments [AutomationRule.fireCount]. Called by the
     * engine after actions execute without error.
     */
    suspend fun recordFire(id: String, timestamp: Long)

    // ─── Logs ────────────────────────────────────────────────────────────────

    /**
     * Emits the most recent execution logs for [ruleId], newest first, capped at [limit].
     *
     * [limit] defaults to 100; the engine also prunes server-side to [AutomationEngine.MAX_LOG_ENTRIES_PER_RULE].
     */
    fun observeLogs(ruleId: String, limit: Int = 100): Flow<List<AutomationLog>>

    /**
     * Persists one log entry and prunes the oldest entries so that at most [AutomationEngine.MAX_LOG_ENTRIES_PER_RULE]
     * entries remain for this rule.
     */
    suspend fun addLog(log: AutomationLog)
}
