/*
 * Copyright (c) 2026 Meshtastic LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.meshtastic.core.database.entity

import androidx.room3.ColumnInfo
import androidx.room3.Entity
import androidx.room3.PrimaryKey

/**
 * Persisted representation of one automation rule (ЕСЛИ → ТО).
 *
 * The trigger, conditions list, and actions list are serialised as JSON strings so the schema stays simple while the
 * domain models remain richly typed sealed-class hierarchies.
 *
 * @property id UUID string; generated by the domain layer before insertion.
 * @property name Human-readable label shown in the rule list UI.
 * @property isEnabled Whether the engine should actively observe this rule.
 * @property triggerJson JSON-encoded [org.meshtastic.core.automation.model.AutomationTrigger].
 * @property conditionsJson JSON-encoded [List<AutomationCondition>], may be empty.
 * @property actionsJson JSON-encoded [List<AutomationAction>], at least one element.
 * @property createdAt Epoch-millis of rule creation.
 * @property lastFiredAt Epoch-millis of last successful engine execution, or 0 if never fired.
 * @property fireCount Lifetime number of successful executions.
 */
@Entity(tableName = "automation_rule")
data class AutomationRuleEntity(
    @PrimaryKey @ColumnInfo(name = "id") val id: String,
    @ColumnInfo(name = "name") val name: String,
    @ColumnInfo(name = "is_enabled", defaultValue = "1") val isEnabled: Boolean = true,
    @ColumnInfo(name = "trigger_json") val triggerJson: String,
    @ColumnInfo(name = "conditions_json", defaultValue = "[]") val conditionsJson: String = "[]",
    @ColumnInfo(name = "actions_json") val actionsJson: String,
    @ColumnInfo(name = "created_at") val createdAt: Long,
    @ColumnInfo(name = "last_fired_at", defaultValue = "0") val lastFiredAt: Long = 0L,
    @ColumnInfo(name = "fire_count", defaultValue = "0") val fireCount: Int = 0,
)
